export interface RioBattingStats {
  doubles: number,
  fair_hits: number,
  foul_hits: number,
  homeruns: number,
  multi_out: number,
  nice_hits: number,
  outs: number,
  perfect_hits: number,
  plate_appearances: number,
  rbi: number,
  sacflys: number,
  singles: number,
  sour_hits: number,
  strikeouts: number,
  summary_at_bats: number,
  summary_doubles: number,
  summary_hits: number,
  summary_homeruns: number,
  summary_rbi: number,
  summary_sac_flys: number,
  summary_singles: number,
  summary_strikeouts: number,
  summary_triples: number,
  summary_walks_bb: number,
  summary_walks_hbp: number,
  triples: number
}
